### ISSUE TITLE
Issue with Jmeter-InfluxDB Writer Plugin v1.1 with Jmeter 3.0

### ISSUE THREAD

**Issue by ciitronian25** [NovaTecConsulting/JMeter-InfluxDB-Writer#1]
Hi 
I have downloaded writer plugin v1.1 and trying to use this with Jmeter V3.0 but i am having issues. I got following error when i click jmeter.bat "An error occured: class com.google.common.collect.AbstractMapBaseMultimap overrides final methond setMap.<Ljava/util/Map;>V errorlevel=1 "

Can you tell me what is the issue? thanks

**Comment by miteshlimbachia** [comment]
Hi I too am experiencing same error, I am using same versions as ciitronian25  and getting same error. this would be a great plugin to use in my case to leverage further benefits of jmeter and influxdb.

when would this be getting a look over...Thanks

**Comment by AlexanderWert** [comment]
Hi,

the only dependencies of this extension are to:
- org.apache.jmeter:ApacheJMeter_core:3.1
- org.apache.jmeter:ApacheJMeter_components:3.1
- org.influxdb:influxdb-java:2.4

So I assume the problem is that this extension only works for JMeter 3.1 and higher. I didn't try to run it with JMeter 3.0.
Another thing you could try is to change the jmeter dependencies to 3.0 and rebuild the binaries after that.

**Comment by AlexanderWert** [comment]
@miteshlimbachia , @ciitronian25 can you confirm that this issue was related to using JMeter version 3.0 instead of JMeter 3.1 ?

**Comment by UshaGo** [comment]
Hi, I am trying to use this plugin with JMeter 4.0. I have installed influxdb 1.6 and grafana 5.3.2
I have downloaded the jar file and restarted jmeter after copying the jar file to lib/ext. When I run the test in Jmeter, I get the following error -

2018-11-01 14:30:08,264 WARN o.a.j.g.u.MenuFactory: Configuration error, probably corrupt or missing third party library(jar)? Could not create class: kg.apc.jmeter.reporters.LoadosophiaUploaderGui.
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/methods/multipart/PartSource

and -

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*
^
	at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_181]
	at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_181]
	at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_181]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_181]
	at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_181]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_181]
	at java.util.regex.Pattern.matches(Unknown Source) ~[?:1.8.0_181]
	at java.lang.String.matches(Unknown Source) ~[?:1.8.0_181]
	at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.handleSampleResults(JMeterInfluxDBBackendListenerClient.java:107) ~[JMeter-InfluxDB-Writer-plugin-1.2.jar:1.2]
	at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:267) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:239) ~[ApacheJMeter_components.jar:4.0 r1823414]
2018-11-01 14:35:11,916 INFO o.a.j.g.a.Start: Stopping test

Appreciate any help to proceed, please !

**Comment by UshaGo** [comment]
Also, I am running this on Windows 7.
