### ISSUE TITLE
Error: "retention policy not found: autogen"

### ISSUE THREAD

**Issue by jacekokrojek** [NovaTecConsulting/JMeter-InfluxDB-Writer#18]
When I try to use JMeter-InfluxDB-Writer I get following error

`
SEVERE: Batch could not be sent. Data will be lost
java.lang.RuntimeException: {"error":"retention policy not found: autogen"}

        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:266)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:167)
        at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:171)
        at org.influxdb.impl.BatchProcessor.flush(BatchProcessor.java:198)
        at org.influxdb.impl.InfluxDBImpl.disableBatch(InfluxDBImpl.java:108)
        at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.teardownTest(JMeterInfluxDBBackendListenerClient.java:147)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:393)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:403)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:498)
        at java.lang.Thread.run(Unknown Source)
`

I user JMeter 3.2 and Java 1.8.0_144

**Comment by dmitryvorobev** [comment]
1. run following command on your influx DB
SHOW RETENTION POLICIES ON your_db_name
2. use name of RETENTION POLICIES from request result in the retentionPolicy parameter in Jmeter Backend Listener.
ps. In my case it looked in Jmeter like:  retentionPolicy default
