### ISSUE TITLE
Issue with Jmeter-InfluxDB Writer Plugin v1.2 with Jmeter 4.0

### ISSUE THREAD

**Issue by UshaGo** [NovaTecConsulting/JMeter-InfluxDB-Writer#26]
Hi, I am trying to use this plugin with JMeter 4.0 on Windows 7. I have installed influxdb 1.6 and grafana 5.3.2
I have downloaded the jar file (v 1.2) and restarted jmeter after copying the jar file to lib/ext. When I run the test in Jmeter, I get the following error -

2018-11-01 14:30:08,264 WARN o.a.j.g.u.MenuFactory: Configuration error, probably corrupt or missing third party library(jar)? Could not create class: kg.apc.jmeter.reporters.LoadosophiaUploaderGui.
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/methods/multipart/PartSource

and -

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*
^
at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_181]
at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_181]
at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_181]
at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_181]
at java.util.regex.Pattern.(Unknown Source) ~[?:1.8.0_181]
at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_181]
at java.util.regex.Pattern.matches(Unknown Source) ~[?:1.8.0_181]
at java.lang.String.matches(Unknown Source) ~[?:1.8.0_181]
at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.handleSampleResults(JMeterInfluxDBBackendListenerClient.java:107) ~[JMeter-InfluxDB-Writer-plugin-1.2.jar:1.2]
at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:267) ~[ApacheJMeter_components.jar:4.0 r1823414]
at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:239) ~[ApacheJMeter_components.jar:4.0 r1823414]
2018-11-01 14:35:11,916 INFO o.a.j.g.a.Start: Stopping test

Appreciate any help to proceed, please !

**Comment by UshaGo** [comment]
It works. I had to close the Jmeter window, restart influxd, disconnected VPN, and  started all these processes again.
