### ISSUE TITLE
If use Retention policy other than default i.e autogen than leads to ``Batch could not be sent. Data will be lost``

### ISSUE THREAD

**Issue by 2012ucp1544** [NovaTecConsulting/JMeter-InfluxDB-Writer#42]
**Scenario** : Created a new Database and new retention policy(35 days).
Running tests with using jmeter-maven-plugin.
Shows error trace in Logs : 

[INFO] Nov 18, 2020 8:32:15 PM org.influxdb.impl.BatchProcessor write
[INFO] SEVERE: Batch could not be sent. Data will be lost
[INFO] java.lang.RuntimeException: {"error":"partial write: points beyond retention policy dropped=47"}
[INFO] 
[INFO] 	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:266)
[INFO] 	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:167)
[INFO] 	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:171)
[INFO] 	at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:188)
[INFO] 	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:153)
[INFO] 	at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.handleSampleResults(JMeterInfluxDBBackendListenerClient.java:152)
[INFO] 	at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:254)
[INFO] 	at org.apache.jmeter.visualizers.backend.BackendListener.access$600(BackendListener.java:50)
[INFO] 	at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:225)

**Comment by amitmalhotra-cell** [comment]
facing same issue

**Comment by AJ84064** [comment]
seems this plugin only works for default retention policy.
